{% set version = "2.4.1" %}

package:
  name: altair
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: ec62eb75df5adb619b9651dbefbdc130e37004508c7ca48da21863100ab114d3

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - entrypoints
    - jinja2
    - jsonschema
    - numpy
    - pandas
    - six
    - toolz
    - typing >=3.6  # [py<35]
  run_constrained:
    - vega >= 1.4
    - jupyterlab >= 0.35

test:
  source_files:
    - altair
  requires:
    - pytest
    - sphinx
    - docutils
    - vega_datasets
    - recommonmark
    - ipython
  commands:
    - python -m pytest --pyargs --doctest-modules altair
  imports:
    - altair
    - altair.examples
    - altair.expr
    - altair.sphinxext
    - altair.utils
    - altair.vega
    - altair.vega.v2
    - altair.vega.v2.schema
    - altair.vega.v3
    - altair.vega.v3.schema
    - altair.vegalite
    - altair.vegalite.v1
    - altair.vegalite.v1.schema
    - altair.vegalite.v2
    - altair.vegalite.v2.schema

about:
  home: http://github.com/altair-viz/altair
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-level declarative visualization library for Python'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
