{% set version = "2.2.1" %}

package:
  name: altair
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: dd5c3df913d4936c337ebfa5d2254844e47da2fca048bcd02d0b798b7a0e0ae7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - entrypoints
    - ipython
    - jsonschema
    - numpy
    - pandas
    - six
    - toolz
    - typing

test:
  source_files:
    - altair
  requires:
    - pytest
    - jinja2
    - sphinx
    - docutils
    - vega_datasets
    - recommonmark
    - ipython
  commands:
    - python -m pytest --pyargs --doctest-modules altair
  imports:
    - altair
    - altair.expr
    - altair.sphinxext
    - altair.utils
    - altair.vega
    - altair.vega.v2
    - altair.vega.v2.schema
    - altair.vega.v3
    - altair.vega.v3.schema
    - altair.vegalite
    - altair.vegalite.v1
    - altair.vegalite.v1.schema
    - altair.vegalite.v2
    - altair.vegalite.v2.examples
    - altair.vegalite.v2.schema

about:
  home: http://github.com/altair-viz/altair
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-level declarative visualization library for Python.'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
