{% set version = "2.1.0" %}

package:
  name: altair
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: e8b222588dde98ec614e6808357fde7fa321118db44cc909df2bf30158d931c0

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - entrypoints
    - ipython
    - jsonschema
    - numpy
    - pandas
    - six
    - toolz
    - typing

test:
  source_files:
    - altair
  requires:
    - docutils
    - jinja2
    - pytest
    - sphinx
    - vega_datasets
  commands:
    - python -m pytest --pyargs --doctest-modules altair
  imports:
    - altair
    - altair.expr
    - altair.sphinxext
    - altair.utils
    - altair.vega
    - altair.vega.v2
    - altair.vega.v2.schema
    - altair.vega.v3
    - altair.vega.v3.schema
    - altair.vegalite
    - altair.vegalite.v1
    - altair.vegalite.v1.schema
    - altair.vegalite.v2
    - altair.vegalite.v2.examples
    - altair.vegalite.v2.schema

about:
  home: http://github.com/altair-viz/altair
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-level declarative visualization library for Python.'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
