{% set name = "altair" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/altair-{{ version }}.tar.gz
  sha256: 46d2b1a9fa29eeed24513262cb1de13a40d55c04580fc21799d5de3991fea8ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - packaging
    - python >=3.8
    - importlib-metadata
    - typing-extensions >=4.0.1
    - jinja2
    - jsonschema >=3.0
    - numpy
    - pandas >=0.25
    - toolz

test:
  source_files:
    - altair
  requires:
    - pytest
    - sphinx
    - docutils
    - vega_datasets
    - recommonmark
    - ipython
    - pip
    - anywidget
  commands:
    - pip check
    - python -m pytest --pyargs --doctest-modules altair
  imports:
    - altair
    - altair.expr
    - altair.utils
    - altair.vegalite

about:
  home: http://altair-viz.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Altair: A declarative statistical visualization library for Python'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
