{% set name = "altair-split" %}
{% set version = "5.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: d960ebe6178c56de3855a68c47b516be38640b73fb3b5111c2a9ca90546dd73d

build:
  number: 0
  noarch: python

outputs:
  - name: altair
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
        - pip
        - hatchling
      run:
        - packaging
        - python >=3.9
        - importlib-metadata
        - typing-extensions >=4.10.0
        - jinja2
        - jsonschema >=3.0
        - narwhals >=1.14.2
    test:
      source_files:
        - altair
      requires:
        - pytest
        - sphinx
        - docutils
        - vega_datasets >=0.9.0
        - anywidget >=0.9.0
        - recommonmark
        - ipython
        - pip
      commands:
        - pip check
        - python -m pytest --pyargs --doctest-modules altair
      imports:
        - altair
        - altair.expr
        - altair.utils
        - altair.vegalite

  - name: altair-all
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
      run:
        - vl-convert-python >=1.7.0
        - pyarrow >=11
        - vegafusion >=2.0.0rc1
        - anywidget >=0.9.0
        - {{ pin_subpackage('altair', exact=True) }}
        - altair_tiles >=0.3.0
      test:
        imports:
          - altair
          - vegafusion
          - vl_convert
          - altair_tiles

about:
  home: http://altair-viz.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Altair: A declarative statistical visualization library for Python'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
    - joelostblom
    - jonmmease
    - binste
    - mattijn
