{% set version = "2.0.1" %}

package:
  name: altair
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: a5ec9878cbfd7e934bc95becb6a50edbbabb93614e7c59ff199b66db856c676e

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - vega 0.4.4
    - traitlets >=4.3.1

test:
  requires:
    - pytest
  imports:
    - altair
    - altair.datasets
    - altair.examples

about:
  home: http://github.com/altair-viz/altair
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-level declarative visualization library for Python.'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
