{% set name = "altair" %}
{% set version = "5.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/altair-{{ version }}.tar.gz
  sha256: 2ad7f0c8010ebbc46319cc30febfb8e59ccf84969a201541c207bc3a4fa6cf81

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

outputs:
  - name: altair
    requirements:
      host:
        - python >=3.8
        - pip
        - hatchling
      run:
        - packaging
        - python >=3.8
        - importlib-metadata
        - typing-extensions >=4.0.1
        - jinja2
        - jsonschema >=3.0
        - numpy
        - pandas >=0.25
        - toolz
    test:
      source_files:
        - altair
      requires:
        - pytest
        - sphinx
        - docutils
        - vega_datasets >=0.9.0
        - anywidget >=0.9.0
        - recommonmark
        - ipython
        - pip
      commands:
        - pip check
        - python -m pytest --pyargs --doctest-modules altair
      imports:
        - altair
        - altair.expr
        - altair.utils
        - altair.vegalite

  - name: altair-all
    requirements:
      host:
        - python >=3.8
      run:
        - vl-convert-python >=1.1.0
        - pyarrow >=11
        - vegafusion-python-embed >=1.5.0
        - {{ pin_subpackage('altair', exact=True) }}
        #   - altair_tiles >=0.3.0
      test:
        imports:
          - altair
          - vegafusion
          - vl-convert-python
          # - altair_tiles

about:
  home: http://altair-viz.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Altair: A declarative statistical visualization library for Python'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
    - joelostblom
    - jonmmease
    - binste
    - mattijn

