{% set name = "altair" %}
{% set version = "4.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/altair-{{ version }}.tar.gz
  sha256: 4939fd9119c57476bf305af9ca0bd1aa7779b2450b874d3623660e879d0fcad1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - entrypoints
    - jinja2
    - jsonschema >=4.5.0
    - numpy >=0.18
    - pandas >=0.18
    - toolz

test:
  source_files:
    - altair
  requires:
    - pytest
    - sphinx
    - docutils
    - vega_datasets
    - recommonmark
    - ipython
    - pip
  commands:
    - pip check
    - python -m pytest --pyargs --doctest-modules altair
  imports:
    - altair
    - altair.examples
    - altair.expr
    - altair.sphinxext
    - altair.tests
    - altair.utils
    - altair.vega
    - altair.vega.v5
    - altair.vega.v5.schema
    - altair.vegalite
    - altair.vegalite.v3
    - altair.vegalite.v3.schema
    - altair.vegalite.v4
    - altair.vegalite.v4.schema

about:
  home: http://altair-viz.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Altair: A declarative statistical visualization library for Python'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
