{% set name = "altair-split" %}
{% set version = "5.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: 5a268b1a0983b23d8f9129f819f956174aa7aea2719ed55a52eba9979b9f6675

build:
  number: 0
  noarch: python

outputs:
  - name: altair
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
        - pip
        - hatchling
      run:
        - packaging
        - python >=3.8
        - importlib-metadata
        - typing-extensions >=4.0.1
        - jinja2
        - jsonschema >=3.0
        - numpy
        - pandas >=0.25
        - toolz
    test:
      source_files:
        - altair
      requires:
        - pytest
        - sphinx
        - docutils
        - vega_datasets >=0.9.0
        - anywidget >=0.9.0
        - recommonmark
        - ipython
        - pip
      commands:
        - pip check
        - python -m pytest --pyargs --doctest-modules altair
      imports:
        - altair
        - altair.expr
        - altair.utils
        - altair.vegalite

  - name: altair-all
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - vl-convert-python >=1.1.0
        - pyarrow >=11
        - vegafusion >=1.5.0
        - vegafusion-python-embed
        - {{ pin_subpackage('altair', exact=True) }}
        - altair_tiles >=0.3.0
      test:
        imports:
          - altair
          - vegafusion
          - vl_convert
          - altair_tiles

about:
  home: http://altair-viz.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Altair: A declarative statistical visualization library for Python'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
    - joelostblom
    - jonmmease
    - binste
    - mattijn
