{% set version = "2.2.2" %}

package:
  name: altair
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: c158699026eb5a19f95c1ca742e2e82bc20c27013ef5785f10836283e2233f8a

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - entrypoints
    - ipython
    - jsonschema
    - numpy
    - pandas
    - six
    - toolz
    - typing  # [py<36]

test:
  source_files:
    - altair
  requires:
    - pytest
    - jinja2
    - sphinx
    - docutils
    - vega_datasets
    - recommonmark
    - ipython
  commands:
    - python -m pytest --pyargs --doctest-modules altair
  imports:
    - altair
    - altair.expr
    - altair.sphinxext
    - altair.utils
    - altair.vega
    - altair.vega.v2
    - altair.vega.v2.schema
    - altair.vega.v3
    - altair.vega.v3.schema
    - altair.vegalite
    - altair.vegalite.v1
    - altair.vegalite.v1.schema
    - altair.vegalite.v2
    - altair.vegalite.v2.examples
    - altair.vegalite.v2.schema

about:
  home: http://github.com/altair-viz/altair
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-level declarative visualization library for Python'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
