schema_version: 1

context:
  version: "6.3.0"

recipe:
  name: altair-meta
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/altair/altair-${{ version }}.tar.gz
  sha256: fa632121aca6d0fcb198a3d8a9f7d937fa5b7518ec947951cfffb44e736d97c8

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: altair
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - versioningit
      run:
        - packaging
        - python >=${{ python_min }}
        - importlib-metadata
        - typing_extensions >=4.12.0
        - jinja2
        - jsonschema >=3.0
        - narwhals >=2.4.0
    tests:
      - python:
          imports: altair
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - "*"
      - requirements:
          run:
            - python ${{ python_min }}.*
            - anywidget >=0.9.0
            - docutils
            - ipython
            - pandas >=1.5.3
            - pip
            - polars >=0.20.3
            - pytest
            - recommonmark
            - sphinx
        script:
          - python -m pytest --pyargs --doctest-modules altair

  - package:
      name: altair-all
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("altair", exact=True) }}
        - altair_tiles >=0.3.0
        - anywidget >=0.9.0
        - narwhals >=2.4.0
        - pandas >=1.5.3
        - pyarrow >=11
        - python >=${{ python_min }}
        - vegafusion >=2.0.3
        - vl-convert-python >=1.9.0
    tests:
      - python:
          imports:
            - altair
            - vegafusion
            - vl_convert
            - altair_tiles
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - "*"

about:
  summary: "Vega-Altair: A declarative statistical visualization library for Python."
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/altair/
  repository: https://github.com/vega/altair
  documentation: https://altair-viz.github.io

extra:
  recipe-maintainers:
    - binste
    - ellisonbg
    - jakevdp
    - joelostblom
    - jonmmease
    - mattijn
    - ocefpaf
