appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AHOI5fA5tw4NkevbRfJWu9MLjmuw30hJTKIV+jPj6THdy2vMhlqvMbJU7odGATGDnV4xTEZ3LdnYHGNXHwaeUXzF56K+boXKWcFae+Ie+h6hn4WsA3szCTBRLU8qSVJlT0k4okFbVch2J3dtJha7RWCX/FHIMnGe5AWJD1/UAaZQOzFs/TGVe6p9vUlIbEZMAyt/V5e+bTEbCRK63JmslMioJDm9vcAYJR506GR0bchdOD7r1e6lo3wCTW9Audz8xYCqLp5l3ztJFTPmWbNce3ISTjOI5XDzi4sXmNAMe/vGisFESaxdkgsgurejGSIPRPezVik8Rf1e7VJyaHmZbwhjxlkTqsw430A4XAs5WabPFjpGUqO3W/3t4LkWE4KwfdLg6JU3jeNcH+7spWMwsXAjnNndThfaWP99fzcQj0g5Mjy1J1wCfAI/Ji0C1Iemdl/nyt5U79txrgWZHFPlFSG4ZoX3MjfszTKR+MS6wwiKqiNMpHoEHUwwtUqV2AuS0MrJf5cBEtl5NWbVlIsce0n+kR7wUfmwW1hIps+kXxzv3Ug+bb8pbvD9psb2eYOlah45G0+Z2Bg6Z150ZOoV6ikhhc82gKzgyzVbQuIoWL+XYLNpR7X805EuaAIjEWaIJapG/Gu0fjH17aU+tTue3crRcjDwQguSi3yYNguA3kM=}
